export const grades = [
  { display: "1", value: "Grade 1" },
  { display: "1/2", value: "Grade 1/2 split" },
  { display: "2", value: "Grade 2" },
  { display: "2/3", value: "Grade 2/3 split" },
  { display: "3", value: "Grade 3" },
  { display: "3/4", value: "Grade 3/4 split" },
  { display: "4", value: "Grade 4" },
  { display: "4/5", value: "Grade 4/5 split" },
  { display: "5", value: "Grade 5" },
  { display: "5/6", value: "Grade 5/6 split" },
  { display: "6", value: "Grade 6" },
  { display: "6/7", value: "Grade 6/7 split" },
  { display: "7", value: "Grade 7" },
  { display: "7/8", value: "Grade 7/8 split" },
  { display: "8", value: "Grade 8" },
];
